In [70]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [71]:
import numpy as np

In [72]:
!file "/content/enng[1].xlsx"

/content/enng[1].xlsx: cannot open `/content/enng[1].xlsx' (No such file or directory)

In [73]:
import pandas as pd

In [74]:
data=pd.read_excel('/content/Book1.xlsx')

In [75]:
data1=pd.read_csv('/content/Data Ops - TPR Client Table QA_GDS Test copy TPR Performance Table_Table (63).csv')

In [77]:
data.head()

,tbl,fiscal_year,fiscal_week,date,marketing_demand_gen_cap,spend_usd_client,spend_usd_engg,spend_usd_difference,demand_usd_client,demand_usd_engg,...,clicks_engg,clicks_difference,sessions_client,sessions_engg,sessions_difference,impressions_client,impressions_engg,impressions_difference,Column1,Column2
0,perf_Social_COH_RTL,FY26,FY26 W52,2026-06-27,Demand Generation,121814.770133,121814.770133,0,6646.800000,6646.800000,...,48779.0,0,24048,24048,0,12959460.0,12959460.0,0,NaN,NaN
1,perf_Social_COH_RTL,FY26,FY26 W52,2026-06-27,Demand Capture,193549.490146,193549.490146,0,205223.018046,205223.018046,...,335349.0,0,200052,200052,0,16613655.0,16613655.0,0,NaN,NaN
2,perf_Search_COH_RTL,FY26,FY26 W52,2026-06-27,Demand Generation,0.000000,0.000000,0,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0.0,0,NaN,NaN
3,perf_Search_COH_RTL,FY26,FY26 W52,2026-06-27,Demand Capture,258349.680000,258349.680000,0,828585.393331,828585.393331,...,417843.0,0,309121,309121,0,28892713.0,28892713.0,0,NaN,NaN
4,perf_Display_COH_RTL,FY26,FY26 W52,2026-06-27,Demand Capture,76991.710000,76991.710000,0,6932.250000,6932.250000,...,69507.0,0,23429,23429,0,5646037.0,5646037.0,0,NaN,NaN

In [79]:
# split the tbl column
data[['temp','channel','brand','site']] = data['tbl'].str.split('_', expand=True)

# temp column remove
data = data.drop(columns=['temp'])

# check output
print(data[['tbl','channel','brand','site']].head())

                    tbl  channel brand site
0   perf_Social_COH_RTL   Social   COH  RTL
1   perf_Social_COH_RTL   Social   COH  RTL
2   perf_Search_COH_RTL   Search   COH  RTL
3   perf_Search_COH_RTL   Search   COH  RTL
4  perf_Display_COH_RTL  Display   COH  RTL

In [80]:
data.columns

Index(['tbl', 'fiscal_year', 'fiscal_week', 'date', 'marketing_demand_gen_cap',
       'spend_usd_client', 'spend_usd_engg', 'spend_usd_difference',
       'demand_usd_client', 'demand_usd_engg', 'demand_usd_difference',
       'clicks_client', 'clicks_engg', 'clicks_difference', 'sessions_client',
       'sessions_engg', 'sessions_difference', 'impressions_client',
       'impressions_engg', 'impressions_difference', 'Column1', 'Column2',
       'channel', 'brand', 'site'],
      dtype='object')

In [81]:
perf= data[['date','brand','channel','site',
             'spend_usd_engg',
             'demand_usd_engg',
             'clicks_engg',
             'sessions_engg',
             'impressions_engg']]

In [82]:
perf['brand'] = perf['brand'].replace({
    'COH': 'Coach',
    'KS': 'Kate Spade'
})

/tmp/ipykernel_9201/4077005918.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  perf['brand'] = perf['brand'].replace({

In [83]:
# Channel changes
perf['channel'] = perf['channel'].replace({
    'Search': 'Paid Search',
    'Social': 'Paid Social'
})

# Site changes based on brand + site
perf.loc[
    (perf['site'] == 'RTL') &
    (perf['brand'] == 'Coach'),
    'site'
] = 'Coach Retail'

perf.loc[
    (perf['site'] == 'RTL') &
    (perf['brand'] == 'Kate Spade'),
    'site'
] = 'K.Spade Retail'

perf.loc[
    (perf['site'] == 'OTL') &
    (perf['brand'] == 'Coach'),
    'site'
] = 'Coach Outlet'

perf.loc[
    (perf['site'] == 'OTL') &
    (perf['brand'] == 'Kate Spade'),
    'site'
] = 'K.Spade Outlet'

# Check output
print(perf[['brand','channel','site']].head())

   brand      channel          site
0  Coach  Paid Social  Coach Retail
1  Coach  Paid Social  Coach Retail
2  Coach  Paid Search  Coach Retail
3  Coach  Paid Search  Coach Retail
4  Coach      Display  Coach Retail

/tmp/ipykernel_9201/2570954966.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  perf['channel'] = perf['channel'].replace({

In [60]:
perf.head(50)

,date,brand,channel,site,spend_usd_engg,demand_usd_engg,clicks_engg,sessions_engg,impressions_engg
0,2026-06-27,Coach,Paid Social,Coach Retail,121814.770133,6646.800000,48779.0,24048,12959460.0
1,2026-06-27,Coach,Paid Social,Coach Retail,193549.490146,205223.018046,335349.0,200052,16613655.0
2,2026-06-27,Coach,Paid Search,Coach Retail,0.000000,0.000000,0.0,0,0.0
3,2026-06-27,Coach,Paid Search,Coach Retail,258349.680000,828585.393331,417843.0,309121,28892713.0
4,2026-06-27,Coach,Display,Coach Retail,76991.710000,6932.250000,69507.0,23429,5646037.0
5,2026-06-27,Coach,Display,Coach Retail,92626.038503,0.000000,2156.0,576,6936281.0
6,2026-06-27,Kate Spade,Display,K.Spade Retail,132056.692370,0.000000,17154.0,6744,11710123.0
7,2026-06-27,Kate Spade,Display,K.Spade Retail,0.000000,0.000000,0.0,0,0.0
8,2026-06-27,Kate Spade,Display,K.Spade Retail,0.000000,0.000000,0.0,67,0.0
9,2026-06-27,Kate Spade,Affiliates,K.Spade Retail,4346.292429,11482.180000,0.0,3252,0.0
10,2026-06-27,Kate Spade,Affiliates,K.Spade Retail,0.000000,0.000000,0.0,0,0.0
11,2026-06-27,Kate Spade,Paid Search,K.Spade Outlet,69756.993536,150787.650000,82842.0,68234,5432175.0
12,2026-06-27,Kate Spade,Paid Search,K.Spade Outlet,0.000000,0.000000,0.0,0,0.0
13,2026-06-27,Kate Spade,Paid Social,K.Spade Retail,11055.590000,0.000000,18289.0,16751,1033114.0
14,2026-06-27,Kate Spade,Paid Social,K.Spade Retail,18544.070001,23522.910000,27176.0,22772,705731.0
15,2026-06-27,Kate Spade,Paid Social,K.Spade Retail,0.000000,0.000000,0.0,0,0.0
16,2026-06-27,Kate Spade,Paid Search,K.Spade Retail,0.000000,0.000000,0.0,0,0.0
17,2026-06-27,Kate Spade,Paid Search,K.Spade Retail,15160.676758,23239.000000,17465.0,15004,971814.0
18,2026-06-27,Kate Spade,Display,K.Spade Outlet,0.000000,0.000000,0.0,0,0.0
19,2026-06-27,Kate Spade,Display,K.Spade Outlet,6893.313863,3354.000000,8235.0,5354,411723.0
20,2026-06-27,Kate Spade,Display,K.Spade Outlet,0.000000,0.000000,0.0,0,0.0
21,2026-06-27,Kate Spade,Affiliates,K.Spade Outlet,21076.558286,51111.570000,0.0,8743,0.0
22,2026-06-27,Kate Spade,Affiliates,K.Spade Outlet,0.000000,0.000000,0.0,0,0.0
23,2026-06-27,Kate Spade,Paid Social,K.Spade Outlet,67003.990000,221.000000,31937.0,34611,6940302.0
24,2026-06-27,Kate Spade,Paid Social,K.Spade Outlet,164729.219997,168886.550000,217352.0,175502,9451738.0
25,2026-06-27,Kate Spade,Paid Social,K.Spade Outlet,0.000000,0.000000,0.0,0,0.0
26,2026-06-26,Coach,Paid Social,Coach Retail,119981.470216,2565.500000,41186.0,20603,11289601.0
27,2026-06-26,Coach,Paid Social,Coach Retail,181949.950216,185879.396012,280061.0,171127,17120688.0
28,2026-06-26,Coach,Paid Search,Coach Retail,0.000000,0.000000,0.0,0,0.0
29,2026-06-26,Coach,Paid Search,Coach Retail,261972.160000,877478.061287,400547.0,309948,27649960.0
30,2026-06-26,Coach,Display,Coach Retail,191225.577357,0.000000,10736.0,1536,10714699.0
31,2026-06-26,Coach,Display,Coach Retail,144412.730000,9391.500000,148672.0,42995,11636179.0
32,2026-06-26,Kate Spade,Display,K.Spade Retail,0.000000,0.000000,0.0,86,0.0
33,2026-06-26,Kate Spade,Display,K.Spade Retail,0.000000,0.000000,0.0,0,0.0
34,2026-06-26,Kate Spade,Display,K.Spade Retail,181264.501161,139.000000,19946.0,6975,15843820.0
35,2026-06-26,Kate Spade,Affiliates,K.Spade Retail,3795.217429,12538.480000,0.0,3525,0.0
36,2026-06-26,Kate Spade,Affiliates,K.Spade Retail,0.000000,0.000000,0.0,0,0.0
37,2026-06-26,Kate Spade,Paid Search,K.Spade Outlet,0.000000,0.000000,0.0,0,0.0
38,2026-06-26,Kate Spade,Paid Search,K.Spade Outlet,71025.890239,142376.000000,77935.0,65946,5828482.0
39,2026-06-26,Kate Spade,Paid Social,K.Spade Retail,0.000000,0.000000,0.0,0,0.0
40,2026-06-26,Kate Spade,Paid Social,K.Spade Retail,10874.130000,0.000000,22875.0,20417,1336347.0
41,2026-06-26,Kate Spade,Paid Social,K.Spade Retail,19897.440006,32733.520000,23172.0,20076,693774.0
42,2026-06-26,Kate Spade,Paid Search,K.Spade Retail,8322.850843,23000.340000,11089.0,10126,455736.0
43,2026-06-26,Kate Spade,Paid Search,K.Spade Retail,0.000000,0.000000,0.0,0,0.0
44,2026-06-26,Kate Spade,Display,K.Spade Outlet,6698.048581,3145.200000,7692.0,5441,414124.0
45,2026-06-26,Kate Spade,Display,K.Spade Outlet,0.000000,0.000000,0.0,0,0.0
46,2026-06-26,Kate Spade,Display,K.Spade Outlet,0.000000,0.000000,0.0,0,0.0
47,2026-06-26,Kate Spade,Affiliates,K.Spade Outlet,0.000000,0.000000,0.0,0,0.0
48,2026-06-26,Kate Spade,Affiliates,K.Spade Outlet,16801.798286,59057.990000,0.0,10089,0.0
49,2026-06-26,Kate Spade,Paid Social,K.Spade Outlet,0.000000,0.000000,0.0,0,0.0

In [84]:
perf.head()

,date,brand,channel,site,spend_usd_engg,demand_usd_engg,clicks_engg,sessions_engg,impressions_engg
0,2026-06-27,Coach,Paid Social,Coach Retail,121814.770133,6646.800000,48779.0,24048,12959460.0
1,2026-06-27,Coach,Paid Social,Coach Retail,193549.490146,205223.018046,335349.0,200052,16613655.0
2,2026-06-27,Coach,Paid Search,Coach Retail,0.000000,0.000000,0.0,0,0.0
3,2026-06-27,Coach,Paid Search,Coach Retail,258349.680000,828585.393331,417843.0,309121,28892713.0
4,2026-06-27,Coach,Display,Coach Retail,76991.710000,6932.250000,69507.0,23429,5646037.0

In [85]:
data1.head(1000)

,fiscal_week,calendar_date,brand,site,channel,spend_usd,demand_usd,clicks,sessions,impressions
0,FY26 W43,19-Apr-26,Coach,Coach Retail,Paid Social,729521.8409,227441.92880,1512767.0,278695,75364521
1,FY26 W40,1-Apr-26,Coach,Coach Retail,Display,566983.7137,10655.50000,165214.0,58337,45496410
2,FY26 W40,4-Apr-26,Coach,Coach Retail,Display,536545.2445,15928.90000,149572.0,56525,35951734
3,FY26 W40,2-Apr-26,Coach,Coach Retail,Display,536023.4593,8620.40000,155315.0,55643,42941628
4,FY26 W40,3-Apr-26,Coach,Coach Retail,Display,535467.1211,8241.30000,156420.0,54923,41574202
...,...,...,...,...,...,...,...,...,...,...
995,FY26 W42,16-Apr-26,Coach,Coach Retail,Referral,0.0000,94723.56085,0.0,24703,0
996,FY26 W43,21-Apr-26,Kate Spade,K.Spade Outlet,Direct,0.0000,57435.93000,0.0,22214,0
997,FY26 W52,24-Jun-26,Kate Spade,K.Spade Retail,Referral,0.0000,2152.02000,0.0,1005,0
998,FY26 W52,23-Jun-26,Kate Spade,K.Spade Retail,Organic Search,0.0000,12151.23000,0.0,13057,0
999,FY26 W43,24-Apr-26,Coach,Coach Retail,Organic Social,0.0000,38897.24267,0.0,8987,0

In [86]:
daily_qa= data1[['calendar_date','brand','channel','site',
             'spend_usd',
             'demand_usd',
             'clicks',
             'sessions',
             'impressions']]

In [87]:
daily_qa.head()

,calendar_date,brand,channel,site,spend_usd,demand_usd,clicks,sessions,impressions
0,19-Apr-26,Coach,Paid Social,Coach Retail,729521.8409,227441.9288,1512767.0,278695,75364521
1,1-Apr-26,Coach,Display,Coach Retail,566983.7137,10655.5000,165214.0,58337,45496410
2,4-Apr-26,Coach,Display,Coach Retail,536545.2445,15928.9000,149572.0,56525,35951734
3,2-Apr-26,Coach,Display,Coach Retail,536023.4593,8620.4000,155315.0,55643,42941628
4,3-Apr-26,Coach,Display,Coach Retail,535467.1211,8241.3000,156420.0,54923,41574202

In [88]:
perf.columns

Index(['date', 'brand', 'channel', 'site', 'spend_usd_engg', 'demand_usd_engg',
       'clicks_engg', 'sessions_engg', 'impressions_engg'],
      dtype='object')

In [89]:
daily_qa.columns

Index(['calendar_date', 'brand', 'channel', 'site', 'spend_usd', 'demand_usd',
       'clicks', 'sessions', 'impressions'],
      dtype='object')

In [90]:
perf.columns=perf.columns.str.strip().str.lower()

daily_qa.columns=daily_qa.columns.str.strip().str.lower()

perf["date"]=pd.to_datetime(perf["date"])

daily_qa["calendar_date"]=pd.to_datetime(daily_qa["calendar_date"])

/tmp/ipykernel_9201/3825487813.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  perf["date"]=pd.to_datetime(perf["date"])
/tmp/ipykernel_9201/3825487813.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  daily_qa["calendar_date"]=pd.to_datetime(daily_qa["calendar_date"])
/tmp/ipykernel_9201/3825487813.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daily_qa["calendar_date"]=pd.to_datetime(daily_qa["calendar_date"])

In [91]:
daily_qa.head()

,calendar_date,brand,channel,site,spend_usd,demand_usd,clicks,sessions,impressions
0,2026-04-19,Coach,Paid Social,Coach Retail,729521.8409,227441.9288,1512767.0,278695,75364521
1,2026-04-01,Coach,Display,Coach Retail,566983.7137,10655.5000,165214.0,58337,45496410
2,2026-04-04,Coach,Display,Coach Retail,536545.2445,15928.9000,149572.0,56525,35951734
3,2026-04-02,Coach,Display,Coach Retail,536023.4593,8620.4000,155315.0,55643,42941628
4,2026-04-03,Coach,Display,Coach Retail,535467.1211,8241.3000,156420.0,54923,41574202

In [92]:
perf.head()

,date,brand,channel,site,spend_usd_engg,demand_usd_engg,clicks_engg,sessions_engg,impressions_engg
0,2026-06-27,Coach,Paid Social,Coach Retail,121814.770133,6646.800000,48779.0,24048,12959460.0
1,2026-06-27,Coach,Paid Social,Coach Retail,193549.490146,205223.018046,335349.0,200052,16613655.0
2,2026-06-27,Coach,Paid Search,Coach Retail,0.000000,0.000000,0.0,0,0.0
3,2026-06-27,Coach,Paid Search,Coach Retail,258349.680000,828585.393331,417843.0,309121,28892713.0
4,2026-06-27,Coach,Display,Coach Retail,76991.710000,6932.250000,69507.0,23429,5646037.0

In [93]:
daily_qa.head()

,calendar_date,brand,channel,site,spend_usd,demand_usd,clicks,sessions,impressions
0,2026-04-19,Coach,Paid Social,Coach Retail,729521.8409,227441.9288,1512767.0,278695,75364521
1,2026-04-01,Coach,Display,Coach Retail,566983.7137,10655.5000,165214.0,58337,45496410
2,2026-04-04,Coach,Display,Coach Retail,536545.2445,15928.9000,149572.0,56525,35951734
3,2026-04-02,Coach,Display,Coach Retail,536023.4593,8620.4000,155315.0,55643,42941628
4,2026-04-03,Coach,Display,Coach Retail,535467.1211,8241.3000,156420.0,54923,41574202

In [94]:
# Perf aggregate
perf_grp = perf.groupby(
    ['date', 'site', 'channel', 'brand'],
    as_index=False
).agg({
    'spend_usd_engg':'sum',
    'demand_usd_engg':'sum',
    'clicks_engg':'sum',
    'sessions_engg':'sum',
    'impressions_engg':'sum'
})

# QA aggregate
daily_qa_grp = daily_qa.groupby(
    ['calendar_date', 'site', 'channel', 'brand'],
    as_index=False
).agg({
    'spend_usd':'sum',
    'demand_usd':'sum',
    'clicks':'sum',
    'sessions':'sum',
    'impressions':'sum'
})

# Merge
combined_df = pd.merge(
    perf_grp,
    daily_qa_grp,
    left_on=['date','site','channel','brand'],
    right_on=['calendar_date','site','channel','brand'],
    how='inner'
)

# Final columns
combined_df = combined_df[[
    'date',
    'site',
    'channel',
    'brand',
    'spend_usd_engg',
    'demand_usd_engg',
    'clicks_engg',
    'sessions_engg',
    'impressions_engg',
    'spend_usd',
    'demand_usd',
    'clicks',
    'sessions',
    'impressions'
]]

combined_df.head()

,date,site,channel,brand,spend_usd_engg,demand_usd_engg,clicks_engg,sessions_engg,impressions_engg,spend_usd,demand_usd,clicks,sessions,impressions
0,2026-06-01,Coach Retail,Display,Coach,460450.752187,6.538200e+03,55630.0,18380,24457320.0,460450.7522,6.538200e+03,55630.0,18380,24457320
1,2026-06-01,Coach Retail,Paid Search,Coach,273476.500000,1.112079e+06,529108.0,362109,35863812.0,273476.5000,1.112079e+06,529108.0,362109,35863812
2,2026-06-01,Coach Retail,Paid Social,Coach,272708.671075,2.249099e+05,474976.0,271787,28923196.0,272708.6711,2.249099e+05,474976.0,271787,28923196
3,2026-06-01,K.Spade Outlet,Affiliates,Kate Spade,30870.585000,2.814680e+04,0.0,8250,0.0,30870.5850,2.814680e+04,0.0,8250,0
4,2026-06-01,K.Spade Outlet,Display,Kate Spade,22682.812428,6.904000e+03,16428.0,14220,1579661.0,22682.2730,6.904000e+03,16428.0,14220,1579642

In [95]:
# Calculate all diff %
combined_df['spend_diff_%'] = (
    abs(combined_df['spend_usd'] - combined_df['spend_usd_engg']) /
    combined_df['spend_usd_engg'].replace(0,1)
) * 100

combined_df['demand_diff_%'] = (
    abs(combined_df['demand_usd'] - combined_df['demand_usd_engg']) /
    combined_df['demand_usd_engg'].replace(0,1)
) * 100

combined_df['clicks_diff_%'] = (
    abs(combined_df['clicks'] - combined_df['clicks_engg']) /
    combined_df['clicks_engg'].replace(0,1)
) * 100

combined_df['sessions_diff_%'] = (
    abs(combined_df['sessions'] - combined_df['sessions_engg']) /
    combined_df['sessions_engg'].replace(0,1)
) * 100

combined_df['impressions_diff_%'] = (
    abs(combined_df['impressions'] - combined_df['impressions_engg']) /
    combined_df['impressions_engg'].replace(0,1)
) * 100


# Add % symbol
diff_cols = ['spend_diff_%','demand_diff_%','clicks_diff_%',
             'sessions_diff_%','impressions_diff_%']

for col in diff_cols:
    combined_df[col] = combined_df[col].round(2).astype(str) + '%'


combined_df.head()

,date,site,channel,brand,spend_usd_engg,demand_usd_engg,clicks_engg,sessions_engg,impressions_engg,spend_usd,demand_usd,clicks,sessions,impressions,spend_diff_%,demand_diff_%,clicks_diff_%,sessions_diff_%,impressions_diff_%
0,2026-06-01,Coach Retail,Display,Coach,460450.752187,6.538200e+03,55630.0,18380,24457320.0,460450.7522,6.538200e+03,55630.0,18380,24457320,0.0%,0.0%,0.0%,0.0%,0.0%
1,2026-06-01,Coach Retail,Paid Search,Coach,273476.500000,1.112079e+06,529108.0,362109,35863812.0,273476.5000,1.112079e+06,529108.0,362109,35863812,0.0%,0.0%,0.0%,0.0%,0.0%
2,2026-06-01,Coach Retail,Paid Social,Coach,272708.671075,2.249099e+05,474976.0,271787,28923196.0,272708.6711,2.249099e+05,474976.0,271787,28923196,0.0%,0.0%,0.0%,0.0%,0.0%
3,2026-06-01,K.Spade Outlet,Affiliates,Kate Spade,30870.585000,2.814680e+04,0.0,8250,0.0,30870.5850,2.814680e+04,0.0,8250,0,0.0%,0.0%,0.0%,0.0%,0.0%
4,2026-06-01,K.Spade Outlet,Display,Kate Spade,22682.812428,6.904000e+03,16428.0,14220,1579661.0,22682.2730,6.904000e+03,16428.0,14220,1579642,0.0%,0.0%,0.0%,0.0%,0.0%

In [96]:
combined_df['date'] = pd.to_datetime(
    combined_df['date']
).dt.date

In [97]:
combined_df.to_excel(
    "qa_output.xlsx",
    index=False,
    engine="openpyxl"
)

In [98]:
from google.colab import files
files.download("qa_output.xlsx")